"""REINFORCE with group baselines for r-lens verbalization.

Ported from mwdf's scripts/train/rl.py, with entropy and KL terms dropped:

- Each step samples `num_prompts` episodes and `group_size` trajectories per
  episode from the SGLang server (temperature from the config; 1.0 keeps the
  REINFORCE estimator exactly on-policy).
- reward = r-lens activation of the verbalized token (lens_reward.py).
- advantage = reward - group mean (REINFORCE with group baselines). One
  optimizer update per rollout keeps the policy on-policy, so there is no
  ratio and no clipping.
- The per-token weight is advantage / (completion tokens generated by ACTIVE
  groups): a group whose trajectories all scored the same has zero advantage
  everywhere, and counting its tokens would shrink the update by the dead
  fraction. Loss = sum_t weight_t * -logp(token_t), accumulated over
  length-sorted microbatches, then a single Adam step on the LoRA params.
- After the step the adapter is saved and synced to the SGLang server.
"""
import dataclasses
import json
import time
from pathlib import Path

import numpy as np
import torch

from .episodes import (EpisodeSampler, load_short_documents, parse_answer,
                       answer_token_id, render_prompt)
from .lens_reward import LensBank, LensRewardModel
from .sglang_client import SGLangServer


def group_advantages(rewards: np.ndarray) -> np.ndarray:
    """rewards [num_prompts, group_size] -> reward minus the group's mean."""
    return rewards - rewards.mean(axis=1, keepdims=True)


def rank_transform(rewards: np.ndarray) -> np.ndarray:
    """Per-group rank-based rewards, linearly spaced over [-1, 1].

    Within each group the raw rewards are ranked (1 = worst ... G = best) and
    mapped to 2*(rank-1)/(G-1) - 1, so the best trajectory gets +1 and the
    worst -1 regardless of the raw reward scale. Ties get their average rank,
    so identical raw rewards transform identically (an all-tied group maps to
    all zeros and stays inactive)."""
    out = np.zeros_like(rewards, dtype=np.float32)
    G = rewards.shape[1]
    if G < 2:
        return out
    for g in range(rewards.shape[0]):
        row = rewards[g]
        order = np.argsort(row, kind="stable")
        sorted_vals = row[order]
        avg_ranks = np.empty(G, dtype=np.float64)
        i = 0
        while i < G:
            j = i
            while j + 1 < G and sorted_vals[j + 1] == sorted_vals[i]:
                j += 1
            avg_ranks[i:j + 1] = (i + j) / 2 + 1  # 1-based average rank
            i = j + 1
        ranks = np.empty(G, dtype=np.float64)
        ranks[order] = avg_ranks
        out[g] = 2 * (ranks - 1) / (G - 1) - 1
    return out


@dataclasses.dataclass
class Rollout:
    episodes: list
    prompts_text: list[str]
    completions_text: list[str]      # flat, episode-major
    completion_ids: list[list[int]]  # exact sampled token ids, incl. stop
    rewards: np.ndarray              # [num_prompts, group_size], used for advantages
    raw_rewards: np.ndarray          # shaped rewards before the rank transform
    stats: dict


def make_policy(parts, cfg):
    from peft import LoraConfig, PeftModel, get_peft_model
    init_adapter = cfg.get("init_adapter")
    if init_adapter:
        # warm-start: load an existing adapter (e.g. SFT warmstart) as the
        # trainable LoRA; its adapter_config.json defines rank/targets
        print(f"Initializing LoRA from {init_adapter}", flush=True)
        policy = PeftModel.from_pretrained(parts.model, str(init_adapter),
                                           is_trainable=True)
    else:
        # Resolve target suffixes to exact nn.Linear names INSIDE the text
        # decoder: multimodal wrappers (gemma's audio/vision towers) contain
        # same-named projections in modules peft cannot wrap.
        import torch.nn as nn
        prefix = next(name for name, mod in parts.model.named_modules()
                      if mod is parts.text_model)
        suffixes = set(cfg.get("lora_target_modules",
                               ["gate_proj", "up_proj", "down_proj"]))
        target_names = [
            name for name, mod in parts.model.named_modules()
            if name.startswith(prefix + ".")
            and name.rsplit(".", 1)[-1] in suffixes
            and isinstance(mod, nn.Linear)
        ]
        lora = LoraConfig(
            r=cfg.get("lora_rank", 8),
            lora_alpha=cfg.get("lora_alpha", 16),
            use_rslora=True,
            lora_dropout=0.0,
            # MLP-only: attention projections differ in shape between hybrid
            # layer types, which sglang's uniform LoRA buffers cannot hold.
            target_modules=target_names,
            task_type="CAUSAL_LM",
        )
        policy = get_peft_model(parts.model, lora)
    # the torch fallback for the gated delta rule stores huge intermediates;
    # checkpointing keeps the with-grad forward inside memory
    policy.gradient_checkpointing_enable(
        gradient_checkpointing_kwargs={"use_reentrant": False})
    policy.enable_input_require_grads()
    trainable = sum(p.numel() for p in policy.parameters() if p.requires_grad)
    print(f"LoRA params: {trainable:,} trainable", flush=True)
    return policy


class VerbalizerTrainer:
    def __init__(self, cfg: dict, parts, tokenizer, server: SGLangServer,
                 run_dir: Path, adapter_dir: Path):
        self.cfg = cfg
        self.parts = parts
        self.tokenizer = tokenizer
        self.server = server
        self.run_dir = run_dir
        self.adapter_dir = adapter_dir
        self.device = cfg.get("device", "cuda:0")
        self.num_layers = len(parts.layers)

        docs = load_short_documents(cfg["documents_path"], tokenizer,
                                    cfg.get("max_documents"))
        layer_range = cfg.get("layer_range")
        self.sampler = EpisodeSampler(
            docs, self.num_layers, cfg.get("seed", 0),
            layer_range=tuple(layer_range) if layer_range else None)
        bank = LensBank(Path(cfg["lens_dir"]), self.num_layers, self.device)
        self.reward_model = LensRewardModel(
            parts, bank, tokenizer,
            format_penalty=cfg.get("format_penalty", -0.2))

        self.policy = make_policy(parts, cfg)
        # use_cache lives on the text config for multimodal wrappers
        parts.text_model.config.use_cache = False
        self.optimizer = torch.optim.Adam(
            [p for p in self.policy.parameters() if p.requires_grad],
            lr=cfg.get("lr", 5e-5),
            betas=tuple(cfg.get("adam_betas", (0.8, 0.95))))
        self.metrics_fh = (run_dir / "metrics.jsonl").open("a")
        import random
        self._sample_rng = random.Random(cfg.get("seed", 0) + 1)

    # ---- rollout ----------------------------------------------------------

    def render_chat(self, prompt: str) -> str:
        # enable_thinking=False pre-fills an empty <think> block, so the model
        # answers directly instead of reasoning first
        return self.tokenizer.apply_chat_template(
            [{"role": "user", "content": prompt}],
            tokenize=False, add_generation_prompt=True,
            enable_thinking=self.cfg.get("enable_thinking", False))

    def rollout(self) -> Rollout:
        cfg = self.cfg
        episodes = self.sampler.sample(cfg["num_prompts"])
        prompts = [render_prompt(ep, self.tokenizer, self.num_layers)
                   for ep in episodes]
        rendered = [self.render_chat(p) for p in prompts]
        completions, completion_ids, truncated = self.server.generate(
            rendered, group_size=cfg["group_size"],
            max_new_tokens=cfg.get("max_new_tokens", 1024),
            temperature=cfg.get("temperature", 1.0))
        token_ids = []
        for text in completions:
            ans = parse_answer(text)
            token_ids.append(None if ans is None
                             else answer_token_id(ans, self.tokenizer))
        # On-policy targets: rewards read the CURRENT policy's activations, so
        # the model is trained to report its own present computation. This is
        # not gameable through the reward side: REINFORCE only differentiates
        # the sampled answers' logprobs, never the reward's own dependence on
        # the adapter weights, so the optimizer cannot sculpt activations to
        # match answers -- only improve the answers.
        raw_rewards, reward_stats, hits = self.reward_model.rewards(episodes, token_ids)
        rewards = np.asarray(raw_rewards, np.float32)
        # mwdf-style length shaping: 0 at/above the knee, rising linearly to 1
        # at zero reasoning tokens. Without it the policy collapses to
        # answering instantly with no reasoning and group advantages die.
        min_think = cfg.get("min_think_tokens", 0)
        if min_think > 0:
            think_lens = []
            for text in completions:
                cut = text.find("<answer>")
                think_text = text if cut < 0 else text[:cut]
                think_lens.append(len(self.tokenizer(
                    think_text, add_special_tokens=False)["input_ids"]))
            penalty = np.maximum(min_think - np.asarray(think_lens), 0) / min_think
            rewards = rewards - penalty.astype(np.float32)
            reward_stats = {**reward_stats,
                            "think_len_mean": float(np.mean(think_lens))}
        # a rollout that hits max_new_tokens without finishing is graded with
        # the (negative) format penalty regardless of any parsed answer, and
        # the accuracy stats are recomputed to match (a truncated trajectory
        # is not a success even if an <answer> block was parsed)
        trunc_mask = np.asarray(truncated)
        rewards = np.where(trunc_mask,
                           np.float32(cfg.get("format_penalty", -1.5)), rewards)
        ok = ~trunc_mask
        reward_stats = {
            **reward_stats,
            "truncated_frac": float(trunc_mask.mean()),
            "top1_acc": float(np.mean(np.asarray(hits) & ok)),
            "answered_frac": float(np.mean(
                np.asarray([t is not None for t in token_ids]) & ok)),
        }
        raw = rewards.reshape(cfg["num_prompts"], cfg["group_size"])
        # rank-based rewards: advantages are computed on per-group centered
        # ranks in [-1, 1]; the raw shaped reward is kept for logging
        transformed = (rank_transform(raw)
                       if cfg.get("rank_rewards", True) else raw)
        return Rollout(episodes, rendered, completions, completion_ids,
                       transformed, raw, reward_stats)

    # ---- update -----------------------------------------------------------

    def update(self, rollout: Rollout) -> dict:
        cfg = self.cfg
        tok = self.tokenizer
        group = cfg["group_size"]
        advantages = group_advantages(rollout.rewards).reshape(-1)
        active_group = np.ptp(rollout.rewards, axis=1) > 0
        active_row = np.repeat(active_group, group)

        prompt_ids = [tok(p, add_special_tokens=False)["input_ids"]
                      for p in rollout.prompts_text]
        completion_ids = rollout.completion_ids
        active_generated = sum(len(c) for row, c in enumerate(completion_ids)
                               if active_row[row])

        rows = []
        for row, comp in enumerate(completion_ids):
            if not comp:
                continue
            prompt = prompt_ids[row // group]
            weight = (float(advantages[row]) / max(active_generated, 1)
                      if active_row[row] else 0.0)
            rows.append((prompt + comp, len(prompt), weight))
        # length-sorted microbatches keep padding waste low
        rows.sort(key=lambda r: -len(r[0]))

        micro = cfg.get("micro_batch_size", 8)
        pad_id = tok.pad_token_id or tok.eos_token_id
        loss_total = 0.0
        self.optimizer.zero_grad(set_to_none=True)
        # gradient checkpointing only engages in train mode (all dropout in
        # this setup is 0, so train mode changes nothing else)
        self.policy.train()
        for begin in range(0, len(rows), micro):
            chunk = rows[begin:begin + micro]
            width = max(len(seq) for seq, _, _ in chunk)
            ids = torch.full((len(chunk), width), pad_id, dtype=torch.long)
            mask = torch.zeros((len(chunk), width), dtype=torch.long)
            row_idx, pos_idx, tgt, w_flat = [], [], [], []
            for i, (seq, plen, w) in enumerate(chunk):
                ids[i, :len(seq)] = torch.tensor(seq)
                mask[i, :len(seq)] = 1
                # hidden positions plen-1 .. len(seq)-2 predict the completion
                for p in range(plen - 1, len(seq) - 1):
                    row_idx.append(i)
                    pos_idx.append(p)
                    tgt.append(seq[p + 1])
                    w_flat.append(w)
            ids = ids.to(self.device)
            mask = mask.to(self.device)
            row_idx = torch.tensor(row_idx, device=self.device)
            pos_idx = torch.tensor(pos_idx, device=self.device)
            tgt = torch.tensor(tgt, device=self.device)
            w_flat = torch.tensor(w_flat, dtype=torch.float32, device=self.device)

            # Unembed only the completion positions, in checkpointed chunks:
            # a [P, 248k-vocab] fp32 logits tensor (plus its softmax grads)
            # dominates memory otherwise. Each chunk's logits exist only
            # transiently, in forward and again during its backward recompute.
            hidden = self.parts.text_model(
                input_ids=ids, attention_mask=mask).last_hidden_state
            h = hidden[row_idx, pos_idx]                    # [P, d]

            def ce_chunk(hc, tc, wc):
                logits = self.parts.unembed(hc).float()
                logp = torch.log_softmax(logits, dim=-1)
                return -(wc * logp.gather(-1, tc.unsqueeze(-1)).squeeze(-1)).sum()

            loss = h.new_zeros((), dtype=torch.float32)
            loss_chunk = self.cfg.get("loss_chunk", 2048)
            for s in range(0, h.shape[0], loss_chunk):
                loss = loss + torch.utils.checkpoint.checkpoint(
                    ce_chunk, h[s:s + loss_chunk], tgt[s:s + loss_chunk],
                    w_flat[s:s + loss_chunk], use_reentrant=False)
            loss.backward()
            loss_total += loss.item()
            del hidden, h, loss

        grad_norm = torch.nn.utils.clip_grad_norm_(
            [p for p in self.policy.parameters() if p.requires_grad],
            cfg.get("max_grad_norm", 1.0))
        self.optimizer.step()
        self.policy.eval()

        gen_tokens = sum(len(c) for c in completion_ids)
        return {
            "loss": loss_total,
            "grad_norm": float(grad_norm),
            "reward_mean": float(rollout.raw_rewards.mean()),
            "advantage_abs_mean": float(np.abs(advantages).mean()),
            "active_group_frac": float(active_group.mean()),
            "gen_len_mean": gen_tokens / max(len(completion_ids), 1),
            **rollout.stats,
        }

    # ---- sample printing --------------------------------------------------

    def print_sample_trajectory(self, rollout: Rollout, step: int):
        """Print one randomly chosen trajectory: episode input, the model's
        reasoning, its answer, and the trajectory's reward and advantage."""
        group = self.cfg["group_size"]
        row = self._sample_rng.randrange(len(rollout.completions_text))
        ep = rollout.episodes[row // group]
        text = rollout.completions_text[row]
        cut = text.find("<answer>")
        thinking = (text if cut < 0 else text[:cut])
        thinking = thinking.split("</think>")[0].strip()
        answer = "(no <answer> block)" if cut < 0 else text[cut:].strip()
        reward = float(rollout.raw_rewards.reshape(-1)[row])
        rank_reward = float(rollout.rewards.reshape(-1)[row])
        advantage = float(group_advantages(rollout.rewards).reshape(-1)[row])
        prompt = render_prompt(ep, self.tokenizer, self.num_layers)

        print(f"\n=== sample trajectory (step {step}, traj {row}) ===")
        print(f"[input]\n{prompt}")
        print(f"[thinking]\n{thinking if thinking else '(none)'}")
        print(f"[output] {answer}")
        print(f"[reward] {reward:.4f}  [rank] {rank_reward:+.3f}  "
              f"[advantage] {advantage:+.4f}")
        print("=" * 47 + "\n", flush=True)

    # ---- sync + loop ------------------------------------------------------

    def save_and_sync(self):
        self.policy.save_pretrained(str(self.adapter_dir))
        self.server.sync_lora(self.adapter_dir)

    def train(self, num_steps: int):
        if self.cfg.get("init_adapter"):
            # sync the warm-start adapter to SGLang so the very first
            # rollouts already sample from it
            self.save_and_sync()
        for step in range(1, num_steps + 1):
            t0 = time.perf_counter()
            rollout = self.rollout()
            t1 = time.perf_counter()
            metrics = self.update(rollout)
            t2 = time.perf_counter()
            self.save_and_sync()
            t3 = time.perf_counter()

            row = {"step": step, "rollout_sec": t1 - t0, "update_sec": t2 - t1,
                   "sync_sec": t3 - t2, **metrics}
            self.metrics_fh.write(json.dumps(row) + "\n")
            self.metrics_fh.flush()
            print(f"step {step}/{num_steps} reward={metrics['reward_mean']:.3f} "
                  f"top1={metrics['top1_acc']:.3f} "
                  f"answered={metrics['answered_frac']:.2f} "
                  f"active={metrics['active_group_frac']:.2f} "
                  f"genlen={metrics['gen_len_mean']:.0f} "
                  f"rollout={t1-t0:.1f}s update={t2-t1:.1f}s sync={t3-t2:.1f}s",
                  flush=True)
            if step % self.cfg.get("sample_every", 10) == 0:
                self.print_sample_trajectory(rollout, step)
            if step % self.cfg.get("checkpoint_every", 50) == 0:
                ckpt = self.run_dir / "checkpoints" / f"adapter_step_{step}"
                self.policy.save_pretrained(str(ckpt))
            if step % self.cfg.get("plot_every", 25) == 0 or step == num_steps:
                try:
                    from .plots import write_plots
                    write_plots(self.run_dir)
                except Exception as e:
                    print(f"plotting failed: {e}", flush=True)
